### ISSUE TITLE
is array of feedbacks used in feedback-manager?

### ISSUE THREAD

**Issue by albsierra** [JuezLTI/feedback-manager#6]
https://github.com/KA226-COVID/feedback-manager/blob/bca9d69340bcc3e432d26d532c967f1dd9433170/package.json#L45
Now, any Authorkit exercise with an array of feedbacks in tests is validated. But, is that array used in any strategy of feedback-manager?

**Comment by albsierra** [comment]
Thank you, Marco.

**Comment by zub4t** [comment]
Done. Now the hint strategy can use multiple feedback messages.
